{
  "Header": {
    "Original": "CVE-2023-41164",
    "ID": "CVE-2023-41164"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:3.2.21-1 (bug #1051226)",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:3.2.21-1",
      "BugNo": 1051226
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2023/09/04/1",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2023/09/04/1"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2023/sep/04/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2023/sep/04/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/3f41d6d62929dfe53eda8109b3b836f26645bdce (main)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/3f41d6d62929dfe53eda8109b3b836f26645bdce (main)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/9c51b4dcfa0cefcb48231f4d71cafa80821f87b9 (4.2.5)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/9c51b4dcfa0cefcb48231f4d71cafa80821f87b9 (4.2.5)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/6f030b1149bd8fa4ba90452e77cb3edc095ce54e (3.2.21)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/6f030b1149bd8fa4ba90452e77cb3edc095ce54e (3.2.21)"
    }
  ]
}